export const INITIAL_METRICS = {
  totalMessages: 184520,
  openRate: 99.1,
  replyRate: 34.8,
  aiResolvedRate: 88.4,
  avgResponseTime: '3.4s',
  totalLeads: 4892,
  hotLeads: 412,
  conversions: 846,
  pipelineValue: '$148,200',
  walletBalance: 64.85,
  monthlyQuotaUsed: 72,
};

export const HOURLY_TRAFFIC_DATA = [
  { time: '00:00', messages: 120, aiReplies: 114, leads: 8 },
  { time: '03:00', messages: 85, aiReplies: 81, leads: 5 },
  { time: '06:00', messages: 240, aiReplies: 228, leads: 18 },
  { time: '09:00', messages: 890, aiReplies: 812, leads: 74 },
  { time: '12:00', messages: 1420, aiReplies: 1280, leads: 122 },
  { time: '15:00', messages: 1680, aiReplies: 1490, leads: 148 },
  { time: '18:00', messages: 1350, aiReplies: 1195, leads: 104 },
  { time: '21:00', messages: 720, aiReplies: 654, leads: 52 },
];

export const CHANNEL_DISTRIBUTION = [
  { name: 'WhatsApp Cloud API', value: 68, color: '#25D366' },
  { name: 'Instagram Direct', value: 22, color: '#E1306C' },
  { name: 'FB Messenger', value: 7, color: '#0866FF' },
  { name: 'AI Voice Calls', value: 3, color: '#A855F7' },
];

export const LEAD_STAGES_DATA = [
  { stage: 'New Visitor', count: 1840, fill: '#6366F1' },
  { stage: 'Interested', count: 1420, fill: '#25D366' },
  { stage: 'Product Inquired', count: 960, fill: '#F59E0B' },
  { stage: 'Hot Qualified', count: 412, fill: '#EF4444' },
  { stage: 'Converted', count: 846, fill: '#10B981' },
];

export const INITIAL_CHATS = [
  {
    id: 'c1',
    contactName: 'Priya Sharma',
    avatar: null,
    phone: '+91 98765 43210',
    channel: 'whatsapp',
    tag: 'Hot',
    tagColor: 'red',
    city: 'Mumbai, IN',
    lastSeen: '2m ago',
    unreadCount: 0,
    aiHandled: true,
    sentiment: 'Positive',
    dealValue: '₹24,999',
    attributes: {
      budget: '₹20,000 - ₹30,000',
      productInterest: 'Luxury Linen Bedding 90x72',
      intent: 'Urgent Purchase',
      language: 'English / Hindi',
    },
    notes: [
      { id: 'n1', author: 'Agent Sarah', text: 'Customer asked for express shipping to Bandra West. COD approved.', timestamp: '10m ago' }
    ],
    messages: [
      {
        id: 'm1',
        sender: 'user',
        text: 'Hi, do you have the king size organic linen bedcover in beige?',
        time: '10:24 AM',
        status: 'read',
      },
      {
        id: 'm2',
        sender: 'ai',
        text: 'Hello Priya! 👋 Yes, our Premium 100% Organic King Size Linen Cover (Beige · 90"×72") is in stock and ready to ship today.\n\nPrice is ₹2,499 with complimentary express delivery and Cash on Delivery available.',
        time: '10:24 AM',
        status: 'read',
        tokenCost: '$0.004',
      },
      {
        id: 'm3',
        sender: 'user',
        text: 'Great! Can you confirm if matching pillowcases come with it?',
        time: '10:27 AM',
        status: 'read',
      },
      {
        id: 'm4',
        sender: 'ai',
        text: 'Yes, it includes 2 matching flange pillowcases! Would you like me to reserve one for you with our current 10% launch discount code `LINEN10`?',
        time: '10:27 AM',
        status: 'read',
        tokenCost: '$0.005',
      },
      {
        id: 'm5',
        sender: 'user',
        text: 'Yes please, add COD to Bandra West address.',
        time: '10:30 AM',
        status: 'delivered',
      },
    ],
  },
  {
    id: 'c2',
    contactName: 'David Miller',
    avatar: null,
    phone: '+1 (415) 890-2134',
    channel: 'instagram',
    tag: 'Interested',
    tagColor: 'green',
    city: 'San Francisco, USA',
    lastSeen: '14m ago',
    unreadCount: 1,
    aiHandled: true,
    sentiment: 'Neutral',
    dealValue: '$1,200',
    attributes: {
      budget: '$1,000+',
      productInterest: 'API Automation & Webhooks',
      intent: 'Software Integration',
      language: 'English',
    },
    notes: [],
    messages: [
      {
        id: 'm201',
        sender: 'user',
        text: 'Saw your reel about Meta CAPI integration. Can we trigger events from Shopify webhooks directly?',
        time: '09:40 AM',
        status: 'read',
      },
      {
        id: 'm202',
        sender: 'ai',
        text: 'Hey David! 🚀 Absolutely. WAPPPILOT provides native Shopify & WooCommerce webhooks. Whenever a cart is abandoned or purchase is completed, we post `InitiateCheckout` or `Purchase` directly to Meta Conversions API with 9.8/10 event match quality.',
        time: '09:40 AM',
        status: 'read',
        tokenCost: '$0.006',
      },
      {
        id: 'm203',
        sender: 'user',
        text: 'Can I test this on the free plan or do I need Pro?',
        time: '09:45 AM',
        status: 'delivered',
      },
    ],
  },
  {
    id: 'c3',
    contactName: 'Tariq Al-Mansoor',
    avatar: null,
    phone: '+971 50 234 9812',
    channel: 'whatsapp',
    tag: 'Converted',
    tagColor: 'emerald',
    city: 'Dubai, UAE',
    lastSeen: '1h ago',
    unreadCount: 0,
    aiHandled: false,
    sentiment: 'Delighted',
    dealValue: '$4,800',
    attributes: {
      budget: '$5,000/mo',
      productInterest: 'Enterprise Multi-Agent WhatsApp',
      intent: 'Paid Subscription',
      language: 'Arabic / English',
    },
    notes: [
      { id: 'n2', author: 'Vikram (Account Exec)', text: 'Annual Enterprise agreement signed. Green tick verification submitted to Meta.', timestamp: '1h ago' }
    ],
    messages: [
      {
        id: 'm301',
        sender: 'user',
        text: 'Invoice paid via wire transfer. When will our WABA green tick be live?',
        time: '08:15 AM',
        status: 'read',
      },
      {
        id: 'm302',
        sender: 'agent',
        text: 'Thank you Tariq! We have submitted your official Meta business verification documents. Meta typically reviews official Green Tick badges within 24-48 hours.',
        time: '08:20 AM',
        status: 'read',
      },
    ],
  },
  {
    id: 'c4',
    contactName: 'Elena Rostova',
    avatar: null,
    phone: '+44 7700 900123',
    channel: 'messenger',
    tag: 'Cold',
    tagColor: 'gray',
    city: 'London, UK',
    lastSeen: '3h ago',
    unreadCount: 0,
    aiHandled: true,
    sentiment: 'Inquiry',
    dealValue: '£450',
    attributes: {
      budget: '£300 - £500',
      productInterest: 'Creator Comment-to-DM',
      intent: 'Exploring',
      language: 'English',
    },
    notes: [],
    messages: [
      {
        id: 'm401',
        sender: 'user',
        text: 'Do you have auto comment reply for Instagram posts?',
        time: '06:12 AM',
        status: 'read',
      },
      {
        id: 'm402',
        sender: 'ai',
        text: 'Yes Elena! When anyone comments a keyword like "LINK" or "PRICE", WAPPPILOT instantly comments back and slides into their DMs with the exact product link and coupon code!',
        time: '06:12 AM',
        status: 'read',
        tokenCost: '$0.004',
      },
    ],
  },
];

export const INITIAL_CAMPAIGNS = [
  {
    id: 'camp-1',
    name: 'Diwali Flash Sale 25% VIP Broadcast',
    channel: 'WhatsApp',
    template: 'festive_discount_v3',
    status: 'Active',
    audience: 'High-Intent Leads & VIPs (2,840 contacts)',
    sent: 2840,
    delivered: 2802,
    read: 2710,
    replied: 894,
    conversions: 312,
    revenue: '$14,280',
    cost: '$18.40',
    roas: '776x',
    scheduledTime: 'Today at 10:00 AM',
  },
  {
    id: 'camp-2',
    name: 'Abandoned Cart 1h Recovery Drip',
    channel: 'WhatsApp + IG',
    template: 'cart_recovery_dynamic',
    status: 'Automated Drip',
    audience: 'Shopify Trigger (Real-time)',
    sent: 1420,
    delivered: 1400,
    read: 1362,
    replied: 480,
    conversions: 218,
    revenue: '$9,810',
    cost: '$9.20',
    roas: '1066x',
    scheduledTime: 'Continuous Trigger',
  },
  {
    id: 'camp-3',
    name: 'Webinar RSVP Confirmation & AI Reminders',
    channel: 'WhatsApp',
    template: 'webinar_pass_reminder',
    status: 'Completed',
    audience: 'Registered Leads (950 contacts)',
    sent: 950,
    delivered: 948,
    read: 930,
    replied: 310,
    conversions: 180,
    revenue: '$4,500',
    cost: '$6.15',
    roas: '731x',
    scheduledTime: 'Yesterday at 4:00 PM',
  },
];

export const META_APPROVED_TEMPLATES = [
  {
    id: 'tpl-1',
    name: 'order_shipped_tracker',
    category: 'UTILITY',
    language: 'en_US',
    status: 'APPROVED',
    header: '📦 Your Order is on the way!',
    body: 'Hi {{1}}, your order #{{2}} has been dispatched via {{3}}. Track live delivery status below.',
    footer: 'WAPPPILOT Official Delivery Bot',
    buttons: [
      { type: 'URL', text: 'Track Order', url: 'https://track.wapppilot.com/{{2}}' },
      { type: 'QUICK_REPLY', text: 'Chat with AI Support' }
    ]
  },
  {
    id: 'tpl-2',
    name: 'cart_recovery_discount',
    category: 'MARKETING',
    language: 'en_US',
    status: 'APPROVED',
    header: '🔥 Left something in your bag, {{1}}?',
    body: 'Your selected items are selling fast! Use exclusive code {{2}} at checkout for an extra {{3}} off.',
    footer: 'Offer expires in 6 hours',
    buttons: [
      { type: 'URL', text: 'Complete My Order', url: 'https://store.wapppilot.com/checkout' },
      { type: 'QUICK_REPLY', text: 'Ask about sizing/color' }
    ]
  },
  {
    id: 'tpl-3',
    name: 'otp_account_verification',
    category: 'AUTHENTICATION',
    language: 'en_US',
    status: 'APPROVED',
    header: null,
    body: 'Your WAPPPILOT verification code is {{1}}. Valid for 10 minutes. Never share this code with anyone.',
    footer: 'Security Notification',
    buttons: [
      { type: 'COPY_CODE', text: 'Copy Code', code: '{{1}}' }
    ]
  },
];

export const META_CAPI_EVENTS = [
  {
    id: 'ev-1',
    eventName: 'Purchase',
    eventTime: '10:30 AM',
    channel: 'WhatsApp Webhook',
    userIdentifier: '+91 98765... (Priya S.)',
    value: '₹2,499 INR',
    matchScore: '9.8 / 10',
    status: 'Delivered (HTTP 200)',
  },
  {
    id: 'ev-2',
    eventName: 'Lead',
    eventTime: '10:24 AM',
    channel: 'Instagram Comment-to-DM',
    userIdentifier: 'david_m_sf (David Miller)',
    value: '$1,200 USD',
    matchScore: '9.4 / 10',
    status: 'Delivered (HTTP 200)',
  },
  {
    id: 'ev-3',
    eventName: 'InitiateCheckout',
    eventTime: '10:15 AM',
    channel: 'WhatsApp Catalog',
    userIdentifier: '+971 50 234... (Tariq Al-M)',
    value: '$4,800 USD',
    matchScore: '9.9 / 10',
    status: 'Delivered (HTTP 200)',
  },
  {
    id: 'ev-4',
    eventName: 'ViewContent',
    eventTime: '09:58 AM',
    channel: 'Messenger Bot',
    userIdentifier: 'elena_r (Elena Rostova)',
    value: '£450 GBP',
    matchScore: '9.1 / 10',
    status: 'Delivered (HTTP 200)',
  },
];

export const KNOWLEDGE_BASE_ITEMS = [
  {
    id: 'kb-1',
    title: 'Product Catalog & Pricing 2026',
    category: 'Catalog',
    size: '1.4 MB',
    lastSync: 'Updated 2h ago',
    active: true,
    tokens: '4,280 tokens',
    preview: 'Contains 120 SKUs: Premium Linen, Silk Duvets, Cotton Towels with retail and COD terms.',
  },
  {
    id: 'kb-2',
    title: 'Shipping, Returns & COD Policies',
    category: 'Policy FAQ',
    size: '420 KB',
    lastSync: 'Updated yesterday',
    active: true,
    tokens: '1,850 tokens',
    preview: 'Express 24-48h delivery across India, UAE, US, UK. 14-day hassle free replacement policy.',
  },
  {
    id: 'kb-3',
    title: 'Meta Partner & Green Tick Verification Guide',
    category: 'Onboarding',
    size: '890 KB',
    lastSync: 'Updated 3d ago',
    active: true,
    tokens: '2,900 tokens',
    preview: 'Step-by-step Meta Business Manager verification, WABA ID mapping and display name rules.',
  },
];

export const AI_VOICE_CALL_LOGS = [
  {
    id: 'call-1',
    contact: 'Rajesh Verma (+91 98200 11223)',
    direction: 'Outbound Campaign',
    duration: '1m 48s',
    agentModel: 'Dhigrowth Voice-Agent v3 (0.9s latency)',
    status: 'Qualified Hot Lead',
    sentiment: 'High Intent',
    summary: 'Customer confirmed interest in the 5-seater office suite, requested WhatsApp brochure and callback from sales.',
  },
  {
    id: 'call-2',
    contact: 'Jessica Taylor (+1 650 443 8901)',
    direction: 'Inbound Support',
    duration: '2m 15s',
    agentModel: 'Dhigrowth Voice-Agent v3 (0.8s latency)',
    status: 'Resolved Support Query',
    sentiment: 'Satisfied',
    summary: 'Inquired about order dispatch status. AI looked up order #SD-8821 and provided live tracking URL via SMS & WhatsApp.',
  },
];
